// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/Faq.tsx";
import * as $$$$$$2 from "./sections/Footer.tsx";
import * as $$$$$$3 from "./sections/Header.tsx";
import * as $$$$$$4 from "./sections/Hero.tsx";
import * as $$$$$$5 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$6 from "./sections/Logos.tsx";
import * as $$$$$$7 from "./sections/Testimonials.tsx";
import * as $$$$$$8 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "deco-sites/landing/sections/BlogPosts.tsx": $$$$$$0,
    "deco-sites/landing/sections/Faq.tsx": $$$$$$1,
    "deco-sites/landing/sections/Footer.tsx": $$$$$$2,
    "deco-sites/landing/sections/Header.tsx": $$$$$$3,
    "deco-sites/landing/sections/Hero.tsx": $$$$$$4,
    "deco-sites/landing/sections/ImageWithParagraph.tsx": $$$$$$5,
    "deco-sites/landing/sections/Logos.tsx": $$$$$$6,
    "deco-sites/landing/sections/Testimonials.tsx": $$$$$$7,
    "deco-sites/landing/sections/Theme/Theme.tsx": $$$$$$8,
  },
  "apps": {
    "deco-sites/landing/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/landing/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/landing",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
